### ISSUE TITLE
Group DM Members List Transparency Issue

### ISSUE THREAD

**Issue by Paradox-Wolf** [DiscordStyles/SoftX#10]
The Members list only in Group DMs is transparent and looks very out of place with the rest of the theme as shown here: 

![](https://cdn.discordapp.com/attachments/126228856477712384/907322963236376696/unknown.png)

I found this chunk of code in SoftX.css that seemed to be making it transparent:
```
#app-mount .members-1998pB {
  background: transparent;
  width: 100%;
}
```

So I added this to the end of my Custom CSS in BetterDiscord to fix it: 
```
#app-mount .members-1998pB {
  background: var(--bg-primary);
}
```

And with that, now my Group DM members list looks like this:

![](https://cdn.discordapp.com/attachments/126228856477712384/907341157489590342/unknown.png)
 
I'm not sure if this was intentional or if my "fix" would break anything else. But I'd recommend the change if possible as I much prefer it this way, as do a couple other people I talked with on the BetterDiscord support server.

**Comment by Gibbu** [comment]
Fixed.
