### ISSUE TITLE
Text popup glitching through screen

### ISSUE THREAD

**Issue by Pol-Denis** [DiscordStyles/SoftX#101]
**Describe the bug**  
When discord is in fullscreen, while hovering mute button or parameter button the text popups are glitching through the screen border not showing the text completely.

**To Reproduce**  
1. Use discord with French language
2. Discord must be in fullscreen
3. Hover mute button or parameter button

**Screenshots**  
![image](https://github.com/DiscordStyles/SoftX/assets/97162419/414f0dfa-27b1-41ab-83f6-b06363a1ee2f)
![image](https://github.com/DiscordStyles/SoftX/assets/97162419/1a28af4a-6710-473e-adef-eccd6541b1ff)

**Infomation (please complete the following information):**  
Discord channel: 
OS: Windows 11
Mod: Vencord
Discord language: French

**Comment by Gibbu** [comment]
This I cannot fixed. Discord doesn't provide any information to specifically target these tooltips.
If I tried to fix these ones, it'd brake all other tooltips that are above any element.
