### ISSUE TITLE
TLDR: Theme needs an update it broke on latest update.

### ISSUE THREAD

**Issue by TomieAi** [DiscordStyles/SoftX#106]

**Comment by mariikkkk** [comment]
Yes, I agree, after the update the theme does not work correctly

**Comment by Gibbu** [comment]
I am aware of the issue.

**Comment by BerrieBuffel** [comment]
how long is it going to take to update?

**Comment by TomieAi** [comment]
> Yes, I agree, after the update the theme does not work correctly

i really love your theme xD best theme ever please make it work again xD i cant bear this ugly default theme

**Comment by BerrieBuffel** [comment]
> i really love this theme xD best theme ever please make it work again xD i cant bear this ugly default theme

me too

**Comment by zabersan** [comment]
server list appears to be themed still, however everything else, modal included, have been reverted to the stock look. Take you time and don't rush, that's how bugs are formed 😉

**Comment by Lioncat6** [comment]
Made a pull request!

**Comment by Tremji08** [comment]
Same here, the theme is currently broken

**Comment by Gibbu** [comment]
The issue is fixed thanks to @Lioncat6. Re-enable your theme.
