### ISSUE TITLE
Server Banner Image

### ISSUE THREAD

**Issue by Jaguayo97** [DiscordStyles/SoftX#11]
Not sure if it was intended but server banners don't show up. Is there a way to make them visible?
![Serverbannernormal](https://user-images.githubusercontent.com/61072436/140845159-9369050c-b0dc-491e-b671-b2db2be492af.png)
![Serverbannersoftx](https://user-images.githubusercontent.com/61072436/140845317-e69a8c62-10dc-4745-95f2-a2c2811e0c19.png)

**Comment by Gibbu** [comment]
I did remove them because I didn't have any ideas on how to "implement" them.
Just did a simple fade.
