### ISSUE TITLE
Scroll disabled in setting modal

### ISSUE THREAD

**Issue by R0kkxSynetique** [DiscordStyles/SoftX#115]
**Describe the bug**  
When in the settings modal, it's impossible to scroll the content of the submenu. The sidebar works fine but, when trying to scroll any of the categories content on the right panel, it's impossible.

**To Reproduce**  
1. Activate the theme.
2. go to any categories of the settings modal. eg (My Account)
3. Try to scroll the content.

**Screenshots** 
![scrolling_issue](https://github.com/DiscordStyles/SoftX/assets/60880661/aed5876d-0ef0-4f95-b54e-e1e83a6f5c6f)

**Information (please complete the following information):**  
Discord channel: Stable 281085
OS: Windows 10
Mod: BetterDiscord 1.10.1
Discord language: EN, UK

**Additional context**
* Tested with `all` my plugins `enabled`
* Tested with only `BDFDB`
* Tested with `no` plugins `enabled`
* When disabling SoftX theme, the scroll's working fine
* Theme Version: `deploy` branch on commit [b0843f3](https://github.com/DiscordStyles/SoftX/commit/b0843f34fb47e90229c64419c4fb426871ebc8dc) written `SoftX v1.2.1` in the BD infos

**Comment by Lioncat6** [comment]
Yup, there's been a pull to fix it already 

https://github.com/DiscordStyles/SoftX/pull/114

just waiting on the merge
