### ISSUE TITLE
Font is different

### ISSUE THREAD

**Issue by ReaLadge** [DiscordStyles/SoftX#117]
I don't know if it's got to do with a new update or something but the fonts have been looking different which I'm not really a fan of. This happen within a day or so.

![image](https://github.com/DiscordStyles/SoftX/assets/70264500/17bdcbbc-8fec-43e6-b731-e1743ec18b71)

**Comment by Lioncat6** [comment]
seems like an issue with your themes not loading properly

**Comment by ReaLadge** [comment]
This eventually got fixed after a couple updates. Forgot to report back here.
