### ISSUE TITLE
Horizontal user area

### ISSUE THREAD

**Issue by vapmKK** [DiscordStyles/SoftX#12]
Would be cool if you had the option to choose whether you wanted the user area to be horizontal or vertical.
![image](https://user-images.githubusercontent.com/56170729/141003403-703947ac-a946-42d1-9756-50e1c5c9926a.png)

**Comment by Gibbu** [comment]
I could separate them with a `@import` in the `SoftX.theme.css` file just like the RadialGlow.

**Comment by vapmKK** [comment]
If possible would work great
