### ISSUE TITLE
Profile/Status pop-out text is blurred

### ISSUE THREAD

**Issue by Strana** [DiscordStyles/SoftX#123]
When you click your profile picture on the bottom left, the text (Username, Bio, and other info) is completely blurred. This seems to be present if you have the discord update that shows your custom status as a thought bubble.

![image](https://github.com/DiscordStyles/SoftX/assets/34879226/9c1c4fd7-0ed7-444c-b5d1-8c071d484b32)

Discord channel: _Stable 304187_  
OS: _Windows 10_  
Mod: _BetterDiscord 1.10.2_
_SoftX v1.2.1_

**Comment by Lioncat6** [comment]
looking into it...

**Comment by Lioncat6** [comment]
Fixed! https://github.com/DiscordStyles/SoftX/pull/124
