### ISSUE TITLE
DisplayServerAsChannels support

### ISSUE THREAD

**Issue by HaychBe** [DiscordStyles/SoftX#13]
Suggestion:

Is it possible that this theme could be edited to support the plugin `DisplayServerAsChannels` [https://github.com/mwittrien/BetterDiscordAddons/tree/25958b30a9f969e7a4b30788586fd025ec306193/Plugins/DisplayServersAsChannels](url)

Love this theme, but I also like the minimalistic feel of that plugin also.

**Comment by Gibbu** [comment]
Forgot to tell you, this is fixed.
