### ISSUE TITLE
Status selector doesn't stay open when moving cursor to it

### ISSUE THREAD

**Issue by Strana** [DiscordStyles/SoftX#130]
When moving the cursor to the status selection list, the moment the cursor is in the spot between the button and the list, the list automatically closes, without SoftX active, the list stays open

https://github.com/DiscordStyles/SoftX/assets/34879226/eca9d2bc-46d0-4318-a5b5-b84dd8f13d7f

**Infomation (please complete the following information):**  
Discord channel: _Stable_  
OS: _Windows_  
Mod: _BetterDiscord_

**Comment by FireBoy00** [comment]
I think they fixed it. For me it works just fine.
