### ISSUE TITLE
Top of DMs and Group chats is regular discord color

### ISSUE THREAD

**Issue by Mustafa-Hamade** [DiscordStyles/SoftX#131]
**Describe the bug**  
When I am on a DM chat or group chat the top bar including name of the person/group, call options etc. are all the default discord. the searches icon is also inaccessible behind the minimize button

**To Reproduce**  
Go on a DM or group chat in the DMs list

**Screenshots**  
![image](https://github.com/user-attachments/assets/d102a856-658e-4799-9d65-ec5ccd2b76d2)

**Infomation (please complete the following information):**  
Stable 309278 (3eb3228)
Host 1.0.9153 x64 (49397) 
Build Override: N/A 
Windows 10 64-bit (10.0.19045)
Vencord 9f8c749 (Standalone)
Electron 30.1.0
Chromium 124.0.6367.243

**Comment by FireBoy00** [comment]
Also, the server list is a bit wierd... idk how to describe it, but... the sizes are all wrong (or maybe my perception? idk), also the unread messages indicator is smaller. 
![image](https://github.com/user-attachments/assets/520f310b-02bf-471b-a30a-27bbdcd361f9)

**Comment by Mustafa-Hamade** [comment]
yeah i noticed that, i doesnt rly bother me as much so couldnt be bothered making a report, the main things that trigger me are unthemed areas

**Comment by Mustafa-Hamade** [comment]
Fixed as of latest vencord update
