### ISSUE TITLE
Channels Disappear After Viewing Stream in Fullscreen

### ISSUE THREAD

**Issue by dannokiddo** [DiscordStyles/SoftX#14]
This is if it wasn't in fullscreen.
![image](https://user-images.githubusercontent.com/95088757/143592682-5c5bbdb8-347a-4f70-acb6-ac960abac167.png)

& this is after exiting full screen.
![image](https://user-images.githubusercontent.com/95088757/143592769-c1f0d302-d468-4023-a20c-8e3fd2f29402.png)

As of now to escape & find the channels I have to restart discord.
Goodluck for you to fix it, really appreciate the kewl theme :)

**Comment by Gibbu** [comment]
Sorry for the late response, busy with work.
How do you even acheive this? When I use fullscreen it removes both Guilds and Channels.

**Comment by Gibbu** [comment]
Found the issue. Unfortunately, I cannot fix it.
