### ISSUE TITLE
[Suggestion] The ability to add a custom image as a background

### ISSUE THREAD

**Issue by MysteryTopHat** [DiscordStyles/SoftX#15]
I believe it would be a good addition to the theme to make the background customizable. I tried replacing the background image link with one of my own, but nothing happened. I really like how the theme looks and I think that this could be a good next step.

**Comment by Gibbu** [comment]
You did something wrong then. Use this: https://bdeditor.dev/theme/softx/ if you're not sure on how to edit themes.

**Comment by MysteryTopHat** [comment]
Thanks!
