### ISSUE TITLE
Increase taskbar area + Horizontal server list

### ISSUE THREAD

**Issue by Just5KY** [DiscordStyles/SoftX#16]
Awesome theme BTW, love it.

The taskbar area in windows is really small, it's difficult to left-click and drag.
![image](https://user-images.githubusercontent.com/71321862/146588541-90ea4ede-4a3c-4c4d-a0dc-dcfaff73fd8b.png)

Also, it would be awesome if you add Horizontal server list. after all, it was also made by you.
![image](https://user-images.githubusercontent.com/71321862/146588917-a2032eb6-3274-4213-b33a-fd71be33ad6f.png)

**Comment by Gibbu** [comment]
The dragging area is 9px which should be plenty.
![image](https://user-images.githubusercontent.com/20338746/146616993-1e60f608-2362-49b8-8636-6b66d3ab73aa.png)

Also I am well aware that I made Horizontal Server List and while making SoftX I did know it wouldn't be compatible with HSL as it changes the server list too much. Without extracting the server list code to a separate import there's no possible fix.
