### ISSUE TITLE
Disable vertical settings / mute... tools list

### ISSUE THREAD

**Issue by ChrisFlyGD** [DiscordStyles/SoftX#17]
Hi!

I would like to know is there is a way to disable the fact that the settings, no sound and mute icons are deplaced to a vertical list.
I love to use the horizontal server list theme but i can't because of these icons, i really love this theme so i would like to use both together.

Thanks!

![image](https://user-images.githubusercontent.com/65044746/148651336-c7042162-9891-49b1-9be7-83575f5de54e.png)

**Comment by Gibbu** [comment]
This is finally a thing. If you wish to disable it remove the `@import url("https://discordstyles.github.io/SoftX/VerticalUserArea.css");` from your theme file. If it's not there, no need to worry.
