### ISSUE TITLE
Theme completely broken

### ISSUE THREAD

**Issue by george2781** [DiscordStyles/SoftX#18]
Due to a recent discord (canary) update, all of the class names were shifted and all themes and most plugins on discord canary were broken, this is what the theme looks like with the update applied
![Screenshot (75)](https://user-images.githubusercontent.com/42376099/148662353-33573086-2efe-46fe-808a-89628335ef66.png)
.

**Comment by Gibbu** [comment]
Correct the newest Cancary version has chnaged a lot of things. And won't be fixed until it comes to Stable.
Discord has a history of updating, reverting, updating, changing in span of a couple of hours to days.

It's pretty much a waste of time to actively support Cancary.

**Comment by george2781** [comment]
Aight but I think it should be mentioned that the theme's broken for anyone using powercord since that's canary only.

**Comment by Gibbu** [comment]
You should expect things to be break on a regular basis because of Canary.

**Comment by george2781** [comment]
True, it's just irritating when something as simple as themes on canary just break and you have to either try to fix it yourself or switch to something else that is fixed.

**Comment by Gibbu** [comment]
The Canary update came to Stable. I'm working on the fix right now.
