### ISSUE TITLE
Theme broken

### ISSUE THREAD

**Issue by spnix** [DiscordStyles/SoftX#19]
I don't know how but the create new server can't be accessed while I use the theme. (I Re-downloaded the theme twice.)
![image](https://user-images.githubusercontent.com/47286298/149266857-81610c5d-2e30-4eeb-9ae7-718261c45766.png)

**Comment by Gibbu** [comment]
A little more information would be helpful:
- Discord version
- Operating System
- Client Mod

**Comment by spnix** [comment]
sorry for the late response 

> * Discord version   -  b5fcc5c7ea877af51876348b6a069ad49f228536
> * Operating System - Windows 10 
> * Client Mod -  Powercord

**Comment by Gibbu** [comment]
Either Discord has updated that area again, which won't be fixed if/until it comes to stable. Or you somehow didn't get the latest update.

**Comment by tea8j** [comment]
looks like the same issue as #17

**Comment by Gibbu** [comment]
Not the same.
