### ISSUE TITLE
Screensharing background isn't transparent like other elements after adding own background

### ISSUE THREAD

**Issue by rey384** [DiscordStyles/SoftX#23]
Changed background using "--background-image:" and "--opacity", everything is transparent with background except screensharing. Its solid black. 
Tried to find specific argument to edit this background in source css but can't find it.
![image](https://user-images.githubusercontent.com/39013777/154314288-37b27979-25a2-4425-ad9e-c209f25e9e32.png)

**Comment by Gibbu** [comment]
Would you want it to display the background? I'd find it every distracting to have a video right on top of an image.
