### ISSUE TITLE
So laggy lol

### ISSUE THREAD

**Issue by SpaceN64** [DiscordStyles/SoftX#24]
Is their anyways you can make this theme less laggy for discord, and glitchy? thank thank

**Comment by Gibbu** [comment]
What part is laggy? If it's just opening the settings, I'm pretty sure you can live with that.

**Comment by SpaceN64** [comment]
Scrolling in general is very slow, and laggy. Also some of the system buttons are working, I'll be it slowly which never happens. Also, the buttons get small when you zoom out of discord

**Comment by Gibbu** [comment]
Do you have Hardware Acceleration enabled in Advanced Settings?

**Comment by SpaceN64** [comment]
I've tried it on and off, still same results
