### ISSUE TITLE
Brief description of the bug

### ISSUE THREAD

**Issue by 1Shawn1** [DiscordStyles/SoftX#25]
**Describe the bug**  
Account profile tab, deafen, mute and settings button is missing a background

**To Reproduce**  
Install theme on powercord

**Screenshots**  
https://i.imgur.com/jIfAGnI.png

**Infomation (please complete the following information):**  
Discord channel: Canary
OS: Windows 10
Mod: Powercord
Discord language: Englis
![DiscordCanary_4tlg9YYOMW](https://user-images.githubusercontent.com/43222123/155756895-d895b1d2-081d-4814-8cac-10d9fbfcd871.png)
h

**Comment by Predeactor** [comment]
This issue happens to me too!
Looks like Discord had fun with it's CSS... :/

@1Shawn1 Alternatively, you could do `git checkout 77be36b360301645808022305d5f7cf2d56831ce` if you know how to to have an usable bar, it will be at it's original place.
![image](https://user-images.githubusercontent.com/61093863/156439622-4ba802b9-3319-4e2d-9b0d-cd69c9b0a15c.png)

**Comment by Gibbu** [comment]
Or you could just remove the `@import url("https://discordstyles.github.io/SoftX/VerticalUserArea.css")` inside the `dist/SoftX.theme.css`

**Comment by Chiggy-Playz** [comment]
No fix for this? Loving this theme so far

**Comment by Gibbu** [comment]
Fixed, update your themes.
