### ISSUE TITLE
Channel bar bug

### ISSUE THREAD

**Issue by ilija510** [DiscordStyles/SoftX#26]
---
name: Bug report
about: Channel bar not working properly
title: Channel bar won't reappear after exiting another person's stream
labels: bug
assignees: ''

---

**Describe the bug**  
*The part of the window where channels and DM's are shown disappears after watching stream*

**To Reproduce**  
*Join another person's stream in fullscreen then go back to discord.*  

**Screenshots**  
![Discord_22-03-07 GONKb](https://user-images.githubusercontent.com/45730866/157108100-1a8336cc-d475-4aae-8259-d81e35a9592d.jpg)
![Discord_22-03-07 QJQjF](https://user-images.githubusercontent.com/45730866/157108105-099843e3-2005-4ed1-95c7-d98c157dc738.jpg)

**Infomation:**  
Discord channel: *Stable*  
OS: *Windows*  
Mod: *BetterDiscord*  
Discord language: *en-us*

**Comment by Gibbu** [comment]
Known bug with SpotifyControls that is impossible to fix.
