### ISSUE TITLE
Inbox button and minimize button colliding

### ISSUE THREAD

**Issue by Chiggy-Playz** [DiscordStyles/SoftX#30]
**Describe the bug**  
The inbox button and minimize button collides, and the inbox is on top of the minimize button

**To Reproduce**  
Hover over the minimize button

**Screenshots**  
<img width="348" alt="image" src="https://user-images.githubusercontent.com/49774426/159485875-d28e0001-8d1a-4613-b4f8-5aaacc8853f5.png">

**Infomation (please complete the following information):**  
Discord channel: Canary
OS: Windows
Mod: Powercord
Discord language: English

**Comment by Gibbu** [comment]
This can be fixed by adding and changing `--TB-width: 32px;`

**Comment by tylovejoy** [comment]
If it's a fix, why wouldn't it be committed? 🤔

**Comment by Gibbu** [comment]
Because it's an issue with his window size. Not the theme.

**Comment by Chiggy-Playz** [comment]
> Because it's an issue with his window size. Not the theme.

Shouldn't the theme not depend on my window size? Moreover its just maximized. Not in any funky size. I have a 15" laptop so not a weird screen size too.

**Comment by AestheticGod19** [comment]
i dont see it i am blind or what
