### ISSUE TITLE
Feature Request: Change "New messages" line color

### ISSUE THREAD

**Issue by Chiggy-Playz** [DiscordStyles/SoftX#32]
Why
The current color (black) is hard to see
<img width="617" alt="image" src="https://user-images.githubusercontent.com/49774426/159487166-a0d5d657-1f87-4e8f-9039-a4835489c486.png">
I mean that "50+ new messages"
In normal discord, its blurple. Maybe it could be the accent color in softx?

**Comment by Chiggy-Playz** [comment]
Same could be said for the "You are viewing older messages" bar
<img width="606" alt="image" src="https://user-images.githubusercontent.com/49774426/159489185-51875e99-7d78-4a18-bc2e-96250d709099.png">
Hard to see

**Comment by Gibbu** [comment]
Changed.
