### ISSUE TITLE
Maximizing calls with SpotifyControls enabled causes UI elements to dissapear

### ISSUE THREAD

**Issue by 1bacon** [DiscordStyles/SoftX#35]
**Describe the bug**  
When SpotifyControls by DevilBro is active and a call is maximized, the bottom left button will not reappear, also server channels and the DMs list will be missing. The only way to fix the UI is to restart the client.

**To Reproduce**  
1. Install SpotifyControls and SoftX
2. Maximize a call / voice channel
3. Minimize again

**Screenshots** 
Spotify Controls:
<a target="_blank" rel="noopener noreferrer" href="https://user-images.githubusercontent.com/55542353/160682787-5a01971f-be67-4cb6-9f76-52385e090930.png"><img src="https://user-images.githubusercontent.com/55542353/160682787-5a01971f-be67-4cb6-9f76-52385e090930.png" alt="Spotify Controls" width=250px style="max-width: 100%;"></a>
This button to maximize:
<a target="_blank" rel="noopener noreferrer" href="https://user-images.githubusercontent.com/55542353/160683106-6263e4d2-dbc3-45b5-b562-6f7035fb0d6f.png"><img src="https://user-images.githubusercontent.com/55542353/160683106-6263e4d2-dbc3-45b5-b562-6f7035fb0d6f.png" alt="This button to maximize" width=400px style="max-width: 100%;"></a>
Buttons and DMs gone:
<a target="_blank" rel="noopener noreferrer" href="https://user-images.githubusercontent.com/55542353/160683197-1c52ddbf-eb35-4262-9453-677facb30947.png"><img src="https://user-images.githubusercontent.com/55542353/160683197-1c52ddbf-eb35-4262-9453-677facb30947.png" alt="Buttons and DMs are gone" width=100px style="max-width: 100%;"></a>

**Infomation (please complete the following information):**  
Discord channel: *Stable*  
OS: *Windows*  
Mod: *BetterDiscord*  
Discord language: *English*  

**Additional context**  
This does not happen with other themes, tested; Discord+, Comfy, Clearvision.

**Comment by Gibbu** [comment]
Known issue that I cannot fix. As said in #14
