### ISSUE TITLE
How to remove the windows titlebar without causing a certain issue

### ISSUE THREAD

**Issue by IDKwhatsausername** [DiscordStyles/SoftX#38]
When I tried to remove the "windows title bar" in the code of the CSS code in BetterDiscord, The title bar changed to this - https://imgur.com/a/PDH3z3Y. But that's not what I want. if you can make it to still stay translucent and not completely transparent or tell me how to, I'd be elated.

**Comment by AestheticGod19** [comment]
i need that one to bro
