### ISSUE TITLE
Scroll wheel is bugged

### ISSUE THREAD

**Issue by GloppyBoopin** [DiscordStyles/SoftX#39]
When scrolling to the very bottom of the channels in a discord server, the scrollbar starts to "bounce", not letting to scroll back up

**Comment by Gibbu** [comment]
Not much I can do about that.
Changing the channels list in any way that Discords lazy loading doesn't like will cause this issue. Which is pretty much any change.
Even default Discord can get this bug can happen. Just Discord things.
