### ISSUE TITLE
titlebar 

### ISSUE THREAD

**Issue by Mekucry** [DiscordStyles/SoftX#45]
![image](https://user-images.githubusercontent.com/94920121/169319559-97e03b9c-7831-45fb-931f-98b769e8bae1.png)

**Comment by Gibbu** [comment]
I'm not sure how you get this. I've set my Discord window to less than 900px and I still can't get this.

**Comment by JimTheGhost** [comment]
This happens for me as well at all resolutions

**Comment by RePacked** [comment]
I have this as well.
It seems like the something is going wrong with [_root.scss](https://github.com/DiscordStyles/SoftX/blob/main/src/theme/_root.scss) because the theme loads:
`--TB-header-padding: 125px;`
instead of the correct 155px
