### ISSUE TITLE
Dissapearing settings and channels tab in discord

### ISSUE THREAD

**Issue by iamtermuxer** [DiscordStyles/SoftX#47]
**Describe the bug**  
  Disappearing settings and such things

**To Reproduce**  
Watch a stream in fullscreen and then go to normal state

**Screenshots**  
![image](https://user-images.githubusercontent.com/59870183/170771357-b34cba42-64e7-4cb3-b8ba-e8994f4d5235.png)

**Infomation (please complete the following information):**  
Discord channel: *((Stable/PTB/Canary))*  
OS: Windows 11 64 bit
Mod: BetterDiscord
Discord language: English

**Additional context**  
*((Add any other context about the problem here. Remove if not applicable.))*  

https://user-images.githubusercontent.com/59870183/170771471-7f73b7a6-a4a1-4b56-a8c4-99762b4a86da.mp4

**Comment by iamtermuxer** [comment]
Dont know what Discord channel means

**Comment by Gibbu** [comment]
This is due to Discord hiding them if the channels list is patched by a plugin.
In this case it's SpotifyControls.

There is nothing I can do about this, else it would've been fixed a long time ago.
As said in #14.
