### ISSUE TITLE
add a toggle to disable the chat boxes please

### ISSUE THREAD

**Issue by Milk-3000BPM** [DiscordStyles/SoftX#50]
also which piece of the code do i remove to get rid of them because i had them gone before but discord decided to delete the old file while i wasnt using it now i have to redo it and i dont remember how

**Comment by Gibbu** [comment]
Add these inside the `:root` brackets of your `.theme.css` file:
```
--chat-bubble-bg: transparent;
--chat-bubble-bg-self: transparent;
--chat-bubble-padding: 0;
--chat-bubble-display: block;
```
