### ISSUE TITLE
Windows snapping does not work

### ISSUE THREAD

**Issue by maciejwalendziuk** [DiscordStyles/SoftX#51]
**Describe the bug**  
*When I am trying to move Discord window by its titlebar snapping to sides of the screen seem not to work*  

**To Reproduce**  
*Drag Discord by it titlebar to the sides of the screen. It does not want to snap.*  

**Infomation (please complete the following information):**  
OS: *Windows*  
Mod: *BetterDiscord*

**Comment by maciejwalendziuk** [comment]
After disabling transparency settings it seems to work again but another thing is that titlebar is so small I have a hard time to click it. Can this be fixed somehow?

**Comment by Gibbu** [comment]
Add this inside the `:root` brackets of your .theme.css file.
```
--TB-bar-height: 12px;
```
