### ISSUE TITLE
User profile popout roles are not being colored

### ISSUE THREAD

**Issue by Jaluvshuskies** [DiscordStyles/SoftX#54]
When opening a user profile by clicking a user in a server, the roles listed are all grey instead of their respective colors. If I disable the theme, the colors are displayed. The plugin BetterRoleColors doesn't seem to have an impact on the issue (disabling it did not result in a correct display)

**To Reproduce**  
1. Go to a discord server
2. Click on a user's name to display the popout
3. Look at the "Roles" section and whether the roles are showing their appropriate colors

![image](https://user-images.githubusercontent.com/29661044/177897006-bae13ae6-04eb-440d-ae2f-7c99f66c5c17.png)
See in the above example ^ with roles "Donators" and "SoftX"

**Infomation (please complete the following information):**  
Discord channel: Stable
OS: Windows 10
Mod: BetterDiscord
Discord language: English

I do have other plugins installed, but none of them seem like they would have caused or affected the issue

**Comment by Gibbu** [comment]
Fixed
