### ISSUE TITLE
Title bar hitbox very small

### ISSUE THREAD

**Issue by angel0ms** [DiscordStyles/SoftX#55]
**Describe the bug**  
*The title bar (bar at the top of the screen) has a very small hitbox, therefore making it hard to move Disocrd around the screen.*  

**To Reproduce**  
*Reproducable everywhere on the Discord app, just try to drag the app around and notice how hard it is to get right.*   

**Infomation:**  
Discord channel: *Stable*  
OS: *Windows 11*  
Mod: *BetterDiscord*  
Discord language: *English, US*

**Comment by Gibbu** [comment]
You can increase it by adding this inside the `:root` brackets of your `.theme.css` file:
```
--TB-bar-height: 12px;
```
