### ISSUE TITLE
[Bug] When use with theme ServerColumns, a weird ring will show beside server icon

### ISSUE THREAD

**Issue by RoyalShooter** [DiscordStyles/SoftX#59]
**Describe the bug**  
When use with theme ServerColumns, a weird ring will show beside server icon.

**To Reproduce**  
enable ServerColumns https://betterdiscord.app/theme/ServerColumns
enable SoftX

**Screenshots**  
![img](https://imgur.com/De4qial.png)

**Infomation (please complete the following information):**  
Discord channel: Stable
OS: Windows
Mod: BetterDiscord
Discord language: English

**Additional context**  

First of all, thank you for making this theme, I really like it, and I am not planning to switch to others. I have quite a lot of servers, and I don't like them to lay in one column. So I am looking forward to this theme to fix. This is the best theme for me. Great visibility, great styling.

**Comment by Gibbu** [comment]
That is because DevilBro modifies the pills. I've tried getting the two to work but it was a massive pain.
And I don't intend of fixing it.
