### ISSUE TITLE
Issue with Scrolling

### ISSUE THREAD

**Issue by keatit71** [DiscordStyles/SoftX#6]
Using Latest version 1.01 of SoftX but was an issue in 1.00 as well where the channel list scroll bar glitches out and stops me accessing channels from the list.

![HOei9V0H0r](https://user-images.githubusercontent.com/42551576/138154955-f79f1f24-1e5a-4a8b-955e-6a3728a22ca0.gif)

**Comment by Gibbu** [comment]
It's an issue with Discords Lazy Loading and me increasing the height of items.
Not much I can do other than reducing the size of the channels/members.
