### ISSUE TITLE
Wrong send friend request icon?

### ISSUE THREAD

**Issue by AnimusN7** [DiscordStyles/SoftX#63]
![sfsddsfsdfs](https://user-images.githubusercontent.com/33660463/184551452-8104863f-a941-4379-88fa-711b01f97d54.png)
The icon for sending people a friend request through the popup modal resembles a settings icon

Go to a server, select any member and view their profile. On the left side the 2nd to last button resembles a settings wheel. Was that intentional?

Discord channel: Stable
OS: Windows
Mod: Better Discord  
Discord language: English

**Comment by Gibbu** [comment]
Nope, Discord doesn't provide any information to differentiate between "Send Friend Request" and "Send Message".
So I placed a cog icon instead.
