### ISSUE TITLE
Forums channel type cut off / unsupported

### ISSUE THREAD

**Issue by Jaluvshuskies** [DiscordStyles/SoftX#64]
When opening a forum channel, the text is cut off on the left side from the sidebar, and also on the right side from the member list if the window is narrow enough. If I disable SoftX, the forum channel appears to behave correctly

**To Reproduce**  
1. Go to a discord server
2. Open a forum channel
3. Observe if all text is visible and nothing is cut off

![unknown (1)](https://user-images.githubusercontent.com/29661044/184552760-8852918b-9293-41c7-a4bf-345363a40c59.png)

**Information (please complete the following information):**  
Discord channel: *Stable*  
OS: *Win10*  
Mod: *BetterDiscord*  
Discord language: *English*  

**Additional context**  
N/A

**Comment by Gibbu** [comment]
Fixed.
