### ISSUE TITLE
User Icon corrupted

### ISSUE THREAD

**Issue by Shiftz1x** [DiscordStyles/SoftX#68]
**Describe the bug**  
*((The user's icon has moved + shrunk on the sidebar. Moved on user popout display via server + DM))*  

**To Reproduce**  
*((Open Better Discord/View a profile via a server/View a profile via DM))*  

**Screenshots**  
![image_2022-09-21_190858960](https://user-images.githubusercontent.com/114103363/191579041-57cd4dcc-cacc-4a62-aa27-02db407f3a61.png)
![image_2022-09-21_190921441](https://user-images.githubusercontent.com/114103363/191579108-416e7d34-e4f8-49c3-8ed0-e5dd3f7f8140.png)   
![image_2022-09-21_191439771](https://user-images.githubusercontent.com/114103363/191580087-cddcee7b-ab4f-4dd3-96d3-c8149ac4995a.png)

**Infomation (please complete the following information):**  
Discord channel: *((Stable))*  
OS: *((Windows))*  
Mod: *((BetterDiscord))*  
Discord language: *((English))*  

**Additional context**  
*((Add any other context about the problem here. Remove if not applicable.))*

**Comment by Gibbu** [comment]
This is actually a Discord issue. Happens even with a theme enabled.

**Comment by Shiftz1x** [comment]
Got a fix for me? Or will it fix itself over time because i’ve never seen
it happen before.

**Comment by Ron-LG** [comment]
same bruh

**Comment by reyyzzy** [comment]
same here,it's annoying

**Comment by Ajdj100** [comment]
still working on figuring out the bottom left profile icon, but I got the other ones put in the right place.

`#app-mount .header-S26rhB {
    position: unset;
    display: flex;
    width: 100%;
    justify-content: space-between;
    align-items: flex-end;
    padding: 0 22px;
    box-sizing: border-box;
    margin-top: -74px;
}

.avatarPositionPremiumBanner-2nq2Fy {
    top: 69px;
    left: 15px;
}

.avatarPositionNormal-V4Mjtq {
    top: 7px;
    left: 15px;
}`

**Comment by Ron-LG** [comment]
> Here is my attempt to fix it (by trial and error, but atleast it works for me)
> 
> ```css
> /* Fix bottom avatar button */ 
> #app-mount .panels-3wFtMD > .container-YkUktl .pointerEvents-9SZWKj {
>     width: 42px;
>     height: 42px;
> }
> #app-mount .panels-3wFtMD > .container-YkUktl .avatarStack-3vfSFa {
>     width: 42px;
>     height: 42px;
> }
> #app-mount .panels-3wFtMD > .container-YkUktl .mask-1FEkla foreignObject {
>     width: 42px;
>     height: 42px;
> }
> 
> /* Remove the black behind Popout and Profile Avatar */
> .bannerSVGWrapper-qc0szY mask {
>     display: none;
> }
> ```
> 
> ![image](https://user-images.githubusercontent.com/77253698/193850542-fa3870bf-59f8-4568-8d85-8d5646e466e7.png) ![image](https://user-images.githubusercontent.com/77253698/193850983-9fe059a1-5e11-4681-a09c-45c5a67a83bd.png) ![image](https://user-images.githubusercontent.com/77253698/193850910-7d7fc581-be55-40e9-ba37-7d5a471fcaa8.png)

how to use it, I am bad at scripting ;-;

**Comment by AutumnVN** [comment]
> how to use it, I am bad at scripting ;-;

just add them into custom css or at bottom of the theme file
