### ISSUE TITLE
CANT CLOSE NOTIFICATION

### ISSUE THREAD

**Issue by reyyzzy** [DiscordStyles/SoftX#71]
**Describe the bug**  
cant close notification 

**To Reproduce**  
when any notification like plugin needs to be update appear

**Screenshots**  
![image](https://user-images.githubusercontent.com/89473810/198845695-e68748d4-fb83-4d23-b43b-0daa84dd52c2.png)
  

**Infomation (please complete the following information):**  
Discord channel: Stable
OS: Windows
Mod: BetterDiscord
Discord language: English

**Comment by Gibbu** [comment]
I'll fix it, but you could just press the button to update your plugin.

**Comment by reyyzzy** [comment]
> I'll fix it, but you could just press the button to update your plugin.

yes i know i can close the notification by clicking the update button,but its just annoying u know
