### ISSUE TITLE
[BUG] SoftX user panel pop bug

### ISSUE THREAD

**Issue by BlueStarBRS** [DiscordStyles/SoftX#72]
**Describe the bug**  
the text boxes are out of bound and then not full readabable

**To Reproduce**  hover over the deaf or settings or click on your profile

**Screenshots**  
![image](https://user-images.githubusercontent.com/25110093/200712837-e6ee418c-3be8-43a7-ae31-be83d4a410e4.png)
![image](https://user-images.githubusercontent.com/25110093/200712900-fc3d2769-8e83-4196-b287-d71d742d5c24.png)
![image](https://user-images.githubusercontent.com/25110093/200712993-8144a6ac-b08e-430f-bfed-ea2ce64e51e1.png)

**Infomation **  
![image](https://user-images.githubusercontent.com/25110093/200713389-f585c5c7-33d5-4ffb-ba7a-43f2eceec7ab.png)
Mod: *Better Discord*  
Discord language: *(German)*  

**Additional context**  
first to fix the deaf or settings pop up (text) move it to the right like this as example:
![image](https://user-images.githubusercontent.com/25110093/200713967-f93a25e6-a6e8-4ebb-8460-b8898097ea04.png)

and the same for the user acount panel:
![image](https://user-images.githubusercontent.com/25110093/200714149-c9d37b82-9a4b-4f09-9773-7129512d0053.png)
move it also to the right  like this:
![image](https://user-images.githubusercontent.com/25110093/200714276-668a9417-e65f-411c-b599-f1a6bc0b73c3.png)
or use this custom CSS to deactivate the new panel and make it to the old:

```
}
.accountProfilePopoutWrapper-3GskID .bannerSVGWrapper-qc0szY,
.accountProfilePopoutWrapper-3GskID .avatarWrapper-3y0KZ1,
.accountProfilePopoutWrapper-3GskID .profileBadges-31rDHI,
.accountProfilePopoutWrapper-3GskID .userProfileInner-3F03PX:before,
.accountProfilePopoutWrapper-3GskID .userPopoutOverlayBackground-dKOOda div:not(.menu-1QACrS, .menu-1QACrS *),
.accountProfilePopoutWrapper-3GskID [id="account-divider-1"] {
    display: none;
}
.accountProfilePopoutWrapper-3GskID {
    left: 0;
}
.accountProfilePopoutWrapper-3GskID .userPopoutOverlayBackground-dKOOda {
    margin: 0;
    border-radius: 4px;
}
.accountProfilePopoutWrapper-3GskID > div,
.accountProfilePopoutWrapper-3GskID .menu-KSaHL1 .submenu-1apzyU {
    border-radius: 4px;
    width: 220px;
}

```
it look them like this:
![image](https://user-images.githubusercontent.com/25110093/200715009-9e9b42be-4bde-425c-9fe3-9a940172f2a5.png)

i hope you can fix it :)
(note this css is from BD official server out of channel #css-snipets)
edit:
the user panel bugs out when a rich presence apears / is active (like playing a game or listen to spotify)

**Comment by Gibbu** [comment]
The tooltips overflowing off screen is something I cannot fix.
And I'll fix the user popouts when I can be bothered.

**Comment by BlueStarBRS** [comment]
> The tooltips overflowing off screen is something I cannot fix. And I'll fix the user popouts when I can be bothered.

you can the plugin from server iinfo can it so maybe you also  it make simply own pop ups and makes the stock from discord invisible

**Comment by Gibbu** [comment]
> you can maybe.

If you've got a fix for it, provide it. I know for a fact that default Discord doesn't have any unique selectors for the user control buttons.
