### ISSUE TITLE
Embedded Text channels in VCs dificult to view

### ISSUE THREAD

**Issue by Ehseezed** [DiscordStyles/SoftX#85]
Embedded text channels in Voice Chats difficult to open

Reproduce is just as easy as going into a VC and attempting to open the embedded text chat

**Screenshots**  
![image](https://user-images.githubusercontent.com/97066152/226611558-84ca63fa-1804-44a8-9f6b-f0b640678fac.png)
 
Discord channel: Stable
OS: Windows
Mod: Better Discord
Discord language: English

It is possible to open them from the popout screen, but its not ideal since on that screen the close button is not enlarged on that screen

**Comment by Lioncat6** [comment]
Made a pull https://github.com/DiscordStyles/SoftX/pull/110

**Comment by Lioncat6** [comment]
Fixed!

https://github.com/DiscordStyles/SoftX/pull/111
