### ISSUE TITLE
Brief description of the bug

### ISSUE THREAD

**Issue by Ethereal100** [DiscordStyles/SoftX#87]
**Describe the bug**  
The Vencord import isn't working.

**To Reproduce**  
_((Steps to reproduce the behavior))

**Screenshots**  
![Screenshot 2023-05-17 033649](https://github.com/DiscordStyles/SoftX/assets/133820313/fb875dba-001d-4e21-8adc-dac8c3683d8e)

**Information (please complete the following information):**  
Discord channel: _((Stable))_  
OS: _((Windows))_  
Mod: _((Vencord))_  
Discord language: _((English))_

**Comment by Gibbu** [comment]
Might be GitHub rate limiting you, since vencord is misusing raw links.
A better option would be to use the GH pages link: `https://discordstyles.github.io/SoftX/SoftX.theme.css`
