### ISSUE TITLE
none of my changes do anything to alter the theme's look

### ISSUE THREAD

**Issue by pancakes111213123432453254235** [DiscordStyles/SoftX#89]
i want to disable the glow effect on the theme, and have changed the thing to 0 under the glow in the CSS, but it didnt work and is still glowing

**Comment by Gibbu** [comment]
Can you provide either a theme file or a code snippet? I can't do much when you give me nothing to go off of.

**Comment by pancakes111213123432453254235** [comment]
oh- disregard this completely! you helped me over on discord just earlier
