### ISSUE TITLE
Server icons are overlapping

### ISSUE THREAD

**Issue by sharunkumar** [DiscordStyles/SoftX#9]
![image](https://user-images.githubusercontent.com/715417/139744595-85ba83e4-5053-437a-893e-5b0e7e8ef54d.png)

Version info:
```
Ptb 103145 (10960f2)
BetterDiscord 1.2.4
Host 1.0.1010 Windows 10 64-Bit (10.0.22000)
```

**Comment by Gibbu** [comment]
Fixed.
