### ISSUE TITLE
Server Radius circle not aligned correctly

### ISSUE THREAD

**Issue by TangerineGameDev** [DiscordStyles/SoftX#91]
**Describe the bug**
See title...  

**To Reproduce**  
When changing zoom level (Settings>Appearance>Zoom Level) to 90% the circles around the server icons shift around...

**Screenshots**  
![image](https://github.com/DiscordStyles/SoftX/assets/81909104/e90a2fce-91b7-449d-a985-fcc75c9b8d12)

**Infomation (please complete the following information):**  
Discord channel: PTB
OS: Arch/Linux 
Mod: Vencord
Discord language: English

**Comment by Gibbu** [comment]
Seems fine to me?
![Discord_eVhf351xL8](https://github.com/DiscordStyles/SoftX/assets/20338746/f01c437f-e879-4fa2-8aa1-71511a4cfff1)

**Comment by TangerineGameDev** [comment]
Did you change the scaling to 90%?
It might be different for you…
So change it to something other than 90% and look for when it happens (CTRL+PLUS/MINUS)

**Comment by TangerineGameDev** [comment]
Sometimes it was worse and sometimes it was better with different scalings for me…

> Seems fine to me? ![Discord_eVhf351xL8](https://user-images.githubusercontent.com/20338746/257494006-f01c437f-e879-4fa2-8aa1-71511a4cfff1.png)

Also isn’t it a little of to the right bottom side? Am I crazy XD

**Comment by Gibbu** [comment]
Yes it was at 90% scaling. But it's not something I can fix since it's Electron try to calculate how things are rendered not at the native scaling.

**Comment by TangerineGameDev** [comment]
Really? So is there no way to change the css to accommodate for scaling?

**Comment by TangerineGameDev** [comment]
As it seems like it is practically impossible to do this I will be closing this issue, unless any new news arises...
I will say though, your theme is amazing keep up the good work!

Guess I will have to just stay at 100% scaling, which is a minor annoyance.
