### ISSUE TITLE
Preview on Better discord not working

### ISSUE THREAD

**Issue by Ambushfall** [DiscordStyles/SoftX#93]
[Correct URI](https://gibbu.github.io/ThemePreview/?file=https://cdn.jsdelivr.net/gh/DiscordStyles/SoftX@deploy/SoftX.theme.css)

[Current Incorrect URI](https://gibbu.github.io/ThemePreview/?file=https://cdn.jsdelivr.net/gh/DiscordStyles/SoftX/SoftX.theme.css)

**Comment by Gibbu** [comment]
Send to the head web dev. Should be able to fix it

**Comment by Gibbu** [comment]
Fixed 👍
