### ISSUE TITLE
Most recent stable update breaks server theming

### ISSUE THREAD

**Issue by Strana** [DiscordStyles/SoftX#94]
In the most recent update to discord, the background of the chat container is no longer themed correctly, instead it shows the default discord background.

(Note, some parts of the screenshot are censored to remove unrelated information)
Using a modified version of SoftX, but the unmodified version is affected as well, so I know this isn't caused from my modifications.
![image](https://github.com/DiscordStyles/SoftX/assets/34879226/2ddf7837-cbfa-44f4-b1ab-298e73fbfc02)

Discord channel: Stable 237546 (c8efe13)
OS: Windows 10 64-Bit (10.0.19044)
Mod: Betterdiscord v1.9.3

**Comment by Gibbu** [comment]
Fixed.

**Comment by Strana** [comment]
> Fixed.

can confirm, thanks for the insanely quick fix!
