### ISSUE TITLE
shakey and the option about the status is unclickable 

### ISSUE THREAD

**Issue by TomieAi** [DiscordStyles/SoftX#96]
**Describe the bug**  
shakey and the option about the status is unclickable the one that you can change if you are online invisible or busy.

**To Reproduce**  
just hover your profile below and do it.

**Screenshots**  

https://github.com/DiscordStyles/SoftX/assets/111332073/bdbe34f0-6961-45d0-bb32-946b9757c52c

Discord channel: Stable
OS: win 11
Mod:   Vencord
Discord language: en

**Additional context**  
nothing

**Comment by Yokoxz** [comment]
I have the same bug, it shakes a lot when you hover over Switch Accounts, Set Custom Status, and Online status, the online status doesn't open when clicked.

**Comment by TomieAi** [comment]
it doesn't work on the latest discord now. sad

**Comment by TomieAi** [comment]
hmm, I think all themes broke on the newest discord update for some reason.

**Comment by CommandoReboot** [comment]
have had the same issue for ages, although id rather have that issue than no theme at all

**Comment by Gibbu** [comment]
Fixed
