### ISSUE TITLE
SoftX isnt working as of the discord update on (i think) 25/10/2023

### ISSUE THREAD

**Issue by CommandoReboot** [DiscordStyles/SoftX#97]
**Describe the bug**  
SoftX simply isnt working anymore

**To Reproduce**  
use SoftX on Vencord (i tried both the link and the file)

**Screenshots**  
_((If applicable, add screenshots to help explain your problem))_

**Infomation (please complete the following information):**  
Discord channel: Stable
OS: Windows 10
Mod: Vencord
Discord language: English (UK)
![image](https://github.com/DiscordStyles/SoftX/assets/125565149/74dfbd52-2926-460c-93e7-b4c2a42ec872)

**Additional context**  
you can only tell that softx is even enabled because the dms button (top left) is green instead of blue

**Comment by Teutonicoy** [comment]
Yea very limited features of SoftX are working but I understand cause the new update completely broke Better Discord

**Comment by CommandoReboot** [comment]
> Yea very limited features of SoftX are working but I understand cause the new update completely broke Better Discord

i hope it gets fixed soon, i want to puke everytime i look at discord

**Comment by Gibbu** [comment]
Fixed
