### ISSUE TITLE
Theme is unusable

### ISSUE THREAD

**Issue by neosrc1** [DiscordStyles/SoftX#99]
**Describe the bug**  
The theme is not functional at all. Shifted buttons (most are inaccessible), gargantuan icons, scattered layout, essentailly nothing works as expected.

**To Reproduce**  
Enable SoftX theme (does not matter if via URL or .theme.css file)

**Screenshots**  
![image](https://github.com/DiscordStyles/SoftX/assets/108533354/bb1ba695-79dd-443d-ab03-fdecbe5e9ac2)
![image](https://github.com/DiscordStyles/SoftX/assets/108533354/c528342a-c9fb-4a62-864b-9dc39fc7cea0)

**Infomation (please complete the following information):**  
Discord channel: Stable
OS: Windows
Mod: Vencord 
Discord language: German

**Additional context**  
This has been occurring since the latest pull request got merged.

**Comment by Lioncat6** [comment]
happened after the merge that was supposed to fix it but it seems things went awry...

**Comment by Strana** [comment]
Yep, getting the same thing.

Had to remove the css file from my themes folder to actually use discord again 😶

**Comment by CommandoReboot** [comment]
> happened after the merge that was supposed to fix it but it seems things went awry...
> 
> also for whatever reason when used on Vencord, it causes unbelievable amounts of lag to the point where you have to open the dev console to disable it

how do i disable it...

**Comment by Lioncat6** [comment]
> > happened after the merge that was supposed to fix it but it seems things went awry...
> > also for whatever reason when used on Vencord, it causes unbelievable amounts of lag to the point where you have to open the dev console to disable it
> 
> how do i disable it...

@CommandoReboot 

Basically, as soon as discord starts loading, spam Ctrl+Shift+I, and when the dev console opens, which is just a chrome inspect element, delete the `vencord-themes` or `vencord-custom-themes` elements to remove the theme temporarily, then go into your user settings to remove it. I do also believe there's a config file and or themes folder somewhere but I wasn't able to find it.

**Comment by Gibbu** [comment]
Yeah the dev tools crashing Discord is Discord itself.
I've tried to open the dev tools like 15 times today and it just kept crashing.

I will try and fix It's just really annoying to do so at the moment.

**Comment by Gibbu** [comment]
Finally got it fixed.
